name: Nightly Build (from Develop branch)

on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * *'
  
  push:
    paths-ignore:
      - .github/workflows/**
      - .gitignore
      - build.sh
      - build-aarch64.sh
      - build-jvm.sh
      - LICENSE
      - mvnw
      - mvnw.cmd
      - README.md
      - release.sh
    branches:
      - develop

jobs:
  call-nightly-build:
#    environment: development
    uses: qiot-project/qiot-ubi-all-reusable-workflows/.github/workflows/app-snapshot.yml@main
    # To pass named inputs to a called workflow, use the "with" keyword in a job.
    with:
      JVM: true
    # Use the "secrets" keyword to pass named secrets.
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
      QUAY_USERNAME: ${{ secrets.QUAY_MANUFACTURING_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_MANUFACTURING_PASSWORD }}
    # Workflows that call reusable workflows in the same organization or enterprise
    #  can use the "inherit" keyword to implicitly pass the secrets.
      # secrets: inherit
