name: Test feature build

on:
  workflow_dispatch:
  
  push:
    branches:
      - feature/**
    paths-ignore:
      - .github/workflows/**
      - .gitignore
      - build.sh
      - build-aarch64.sh
      - build-jvm.sh
      - LICENSE
      - mvnw
      - mvnw.cmd
      - README.md
      - release.sh
      
  pull_request:
    branches:
      - feature/**
    paths-ignore:
      - .github/workflows/**
      - .gitignore
      - build.sh
      - build-aarch64.sh
      - build-jvm.sh
      - LICENSE
      - mvnw
      - mvnw.cmd
      - README.md
      - release.sh

jobs:
  call-test-feature-build:
#    environment: development
    uses: andreabattaglia/reusable-workflows/.github/workflows/test-feature.yml@main
    # To pass named inputs to a called workflow, use the "with" keyword in a job.
    # with:
      # JVM: false # Optional - Default true - Enable this input variable if you need your Quarkus app to be compiled in JVM_MODE 
    # Use the "secrets" keyword to pass named secrets.
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
    # Workflows that call reusable workflows in the same organization or enterprise
    #  can use the "inherit" keyword to implicitly pass the secrets.
      # secrets: inherit